# Dependencies
markdown:            kramdown 
highlighter:         rouge 

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               AlhambraMakers 
tagline:             COMUNIDAD MAKER EN GRANADA
description:         'alhambramakers'
url:                 http://alhambramakers.github.io
baseurl:             /
paginate:            5
paginate_path:       '/page:num/'


# About/contact
author:
  name:              alhambramakers 
  url:               http://git.io/alhambramakers
  email:             alhambramakers@linux.com 
  linkedin:          https://ca.linkedin.com/in/alhambramakers
  googleplus:        https://plus.google.com/+AlhambraMakers/
  twitter:           https://twitter.com/alhambramakers

# Timezone
timezone: Europe/Madrid

# Custom vars
version:             1.0.0
customdate:          "%d/%m/%Y"
# Custom gems
gems:
    - jekyll-sitemap
    - jekyll-paginate

# jekyll-tagging params
tag_page_layout: blog_by_tag
tag_page_dir: blog/tag
tag_feed_layout: blog_by_tag
tag_feed_dir: blog/tag
tag_permalink_style: pretty
