# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Simarpreet Singh 
#tagline:             'Singh'
description:          
url:                 http://simar7.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Simarpreet Singh 
  url:               http://git.io/simar 
  email:             simar@linux.com 
  linkedin:          https://ca.linkedin.com/in/simar7
  googleplus:        https://plus.google.com/+SimarpreetSingh/

# Timezone
timezone: America/Toronto

# Custom vars
version:             1.0.0

# Custom gems
gems:
    - jekyll-sitemap

# jekyll-tagging params
tag_page_layout: blog_by_tag
tag_page_dir: blog/tag
tag_feed_layout: blog_by_tag
tag_feed_dir: blog/tag
tag_permalink_style: pretty
